version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper:zookeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
      image: 'mongo:latest'
      ports:
        - '27017:27017'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node