spring:
  application:
      name: player-search-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: devchaos

  cloud:
    stream:
      bindings:
        player-in:
          consumer:
            useNativeEncoding: true
          destination: player.t
          group: player-search-service
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          player-in:
            consumer:
              autoCommitOffset: true
              startOffset: latest
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                key:
                  deserializer: org.apache.kafka.common.serialization.StringDeserializer

  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: io.devchaos.comm.domain

server:
  port: 8081